apps/base/urls.py
"""urlconf for the base application"""

from django.conf.urls import url
from django.views.generic import TemplateView

from .views import ( home, ProfileCreate, ProfileUpdate, ProfileDetail, 
        search_book_title, search_author_name, check_profile )
from .views import make_payment, payment_redirect, payment_webhook, ItemList
from .views import BoxDetail, BoxCreate, PaymentFulfillmentList, BookCreate

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about/$', TemplateView.as_view(template_name="base/about.html"), name="about"),
    url(r'^profile/check/$', check_profile, name='profile-check'),
    url(r'^profile/view/(?P<pk>[^/]+)$', ProfileDetail.as_view(), name='profile-detail'),
    url(r'^profile/add/$', ProfileCreate.as_view(), name='profile-create'),
    url(r'^profile/edit/$', ProfileUpdate.as_view(), name='profile-edit'),
    url(r'^api/books/$', search_book_title, name='search-book'),
    url(r'^api/authors/$', search_author_name, name='search-author'),
    url(r'^payment/create/(?P<pk>[^/]+)$', make_payment, name='payment-create'),
    url(r'^payment/redirect/(?P<pk>[^/]+)$', payment_redirect, name='payment-redirect'),
    url(r'^payment/webhook/$', payment_webhook, name='payment-webhook'),
    url(r'^shop/$', ItemList.as_view(), name='shop'),
    url(r'^privacy/$', TemplateView.as_view(template_name="base/privacy.html"), name="privacy"),
    url(r'^tos/$', TemplateView.as_view(template_name="base/tos.html"), name="tos"),
    url(r'^box/review/(?P<pk>[^/]+)$', BoxDetail.as_view(), name="box-review"),
    url(r'^box/create/(?P<pk>[^/]+)$', BoxCreate.as_view(), name="box-create"),
    url(r'^payment/fulfillment/$', PaymentFulfillmentList.as_view(), name="payment-fulfillment"),
    url(r'^book/add/$', BookCreate.as_view(), name="book-create"),
]

subscriptionbox/urls.py
""" Default urlconf for subscriptionbox """

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import index, sitemap
from django.views.generic.base import TemplateView
from django.views.defaults import (permission_denied,
                                   page_not_found,
                                   server_error)


sitemaps = {
    # Fill me with sitemaps
}

urlpatterns = [
    url(r'', include('base.urls')),
    url(r'^accounts/', include('allauth.urls')), 
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    url(r'^select2/', include('django_select2.urls')),
    # Admin
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Sitemap
    url(r'^sitemap\.xml$', index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps}),

    # robots.txt
    url(r'^robots\.txt$',
        TemplateView.as_view(
            template_name='robots.txt',
            content_type='text/plain')
        ),
]

if settings.DEBUG:
    # Add debug-toolbar
    import debug_toolbar  # noqa
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

    # Serve media files through Django.
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    # Show error pages during development
    urlpatterns += [
        url(r'^403/$', permission_denied),
        url(r'^404/$', page_not_found),
        url(r'^500/$', server_error)
    ]

apps/base/models.py
"""Base models"""

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

STATES = (
    (u'AP', u'ANDHRA PRADESH'),
    (u'AR', u'ARUNACHAL PRADESH'),
    (u'AS', u'ASSAM'),
    (u'BR', u'BIHAR'),
    (u'CG', u'CHATTISGARH'),
    (u'DL', u'DELHI'),
    (u'GA', u'GOA'),
    (u'GJ', u'GUJARAT'),
    (u'HR', u'HARYANA'),
    (u'HP', u'HIMACHAL PRADESH'),
    (u'JK', u'JAMMU & KASHMIR'),
    (u'JS', u'JHARKHAND'),
    (u'KA', u'KARNATAKA'),
    (u'KL', u'KERALA'),
    (u'MP', u'MADHYA PRADESH'),
    (u'MH', u'MAHARASHTRA'),
    (u'MN', u'MANIPUR'),
    (u'ML', u'MEGHALAYA'),
    (u'MZ', u'MIZORAM'),
    (u'NL', u'NAGALAND'),
    (u'OR', u'ORISSA'),
    (u'PB', u'PUNJAB'),
    (u'RJ', u'RAJASTHAN'),
    (u'SK', u'SIKKIM'),
    (u'TN', u'TAMIL NADU'),
    (u'TR', u'TRIPURA'),
    (u'UK', u'UTTARAKHAND'),
    (u'UP', u'UTTAR PRADESH'),
    (u'WB', u'WEST BENGAL'),
    (u'AN', u'ANDAMAN & NICOBAR'),
    (u'CH', u'CHANDIGARH'),
    (u'DN', u'DADAR & NAGAR HAVELI'),
    (u'DD', u'DAMAN & DIU'),
    (u'LD', u'LAKSHADWEEP'),
    (u'PY', u'PONDICHERRY')
)


class Genre(models.Model):
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return u"%s" % self.name

class Publisher(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    country = models.CharField(max_length=64, blank=True)
    website = models.URLField(blank=True)

    def __str__(self):
        return "<Publisher: %s>" % self.name

class Author(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    ol_id = models.CharField(max_length=16, unique=True)
    alternate_names = models.CharField(max_length=1024, blank=True, db_index=True)
    year_of_birth = models.CharField(max_length=50, blank=True)
    year_of_death = models.CharField(max_length=50, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "<Author: %s>" % self.name


class Work(models.Model):
    title = models.CharField(max_length=1024, db_index=True)
    ol_id = models.CharField(max_length=16, unique=True)
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return "<Work: %s>" % self.title

class Book(models.Model):
    title = models.CharField(max_length=1024, db_index=True)
    ol_id = models.CharField(max_length=16, unique=True)
    isbn = models.CharField(max_length=20, blank=True, db_index=True)
    genres = models.ManyToManyField(Genre)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    year_of_publication = models.CharField(max_length=50, blank=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return "<Book: %s>" % self.title

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=64, db_index=True)
    state = models.CharField(max_length=2, choices=STATES, db_index=True)
    postal_code = models.CharField(max_length=8, db_index=True)
    phone_mobile = models.CharField(max_length=13)
    phone_landline = models.CharField(max_length=20, blank=True)
    genres = models.ManyToManyField(Genre)
    favourite_books = models.ManyToManyField(Book, blank=True)
    favourite_authors = models.ManyToManyField(Author, blank=True)
    boxes_remaining = models.IntegerField(default=0)
    interests = models.CharField(max_length=1024, blank=True)

    def __str__(self):
        return "<Profile: %s>" % self.user

    def get_absolute_url(self):
        return reverse('profile-detail', kwargs={'pk': self.id})

class Item(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=255)
    #maximum price of 99999.99
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(upload_to="items", blank=True)
    boxes_added = models.IntegerField()

    def __str__(self):
        return "<Item: %s-%d>" % (self.name, self.price)

class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True, db_index=True)
    payment_id = models.CharField(max_length=64)
    payment_request_id = models.CharField(max_length=64)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    fees = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    longurl = models.URLField()
    shorturl = models.URLField()
    status = models.CharField(max_length=16)
    fulfilled = models.BooleanField(default=False)

    def __str__(self):
        return "<Payment: {}-{}-{}>".format(self.user, self.item, self.payment_date)

class Box(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    shipped_at = models.DateTimeField(null=True, blank=True)
    books = models.ManyToManyField(Book)
    ratings = GenericRelation(Rating, related_query_name='boxes', blank=True)
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    notification_sent = models.BooleanField(default=False)
    tracking_code = models.CharField(max_length=128, db_index=True, blank=True)

    class Meta:
        verbose_name_plural = 'boxes'
        ordering = ['-shipped_at']

apps/base/forms.py
from django import forms
from django_select2.forms import ModelSelect2MultipleWidget, ModelSelect2Widget
from .models import Profile, Book, Author, Box, Publisher

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
                'address', 'city', 'state', 'postal_code', 'phone_mobile', 'phone_landline', 
                'genres', 'interests'
                )
        widgets = {
            'address': forms.Textarea(attrs={'rows': 4, 'cols': 24}),
            'genres': forms.CheckboxSelectMultiple(),
            'interests': forms.Textarea(attrs={'rows': 5, 'cols': 48})
        }

class BoxForm(forms.Form):
    shipped = forms.BooleanField(required=False)
    books = forms.ModelMultipleChoiceField(widget=ModelSelect2MultipleWidget(
        queryset=Book.objects.all(),
        search_fields=['title__icontains'],
        attrs={'data-placeholder': 'Search for Book titles', 'data-width': '20em' }
        ), queryset=Book.objects.all(), required=True)
    tracking_code = forms.CharField(required=False)

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'title', 'ol_id', 'isbn', 'genres', 'authors', 'publisher', 'year_of_publication'
            )
        widgets = {
            'authors': ModelSelect2MultipleWidget(
                queryset=Author.objects.all(),
                search_fields=['name__icontains'],
                attrs={'data-placeholder': 'Search for Author name', 'data-width': '20em' }
            ),
            'publisher': ModelSelect2Widget(
                queryset=Publisher.objects.all(),
                search_fields=['name__icontains'],
                attrs={'data-placeholder': 'Search for Publisher name', 'data-width': '20em'} 
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['authors'].required = False
        self.fields['publisher'].required = False

apps/base/templates/base/_form_field.html
<div class="row">
    <div class="col-sm-2">{{ field.label }}</div>
    <div class="col-sm-4">{{ field }} </div>
</div>

apps/base/templates/base/about.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-2">
      <h1>About</h1>
    </div>
    <div class="col-md-10">
        <p>Goobe's Subscription Box is a service of Goobe's Book Republic, an underground bookstore/library established in 2009 (Yes, we are the kind of fools that started a brick and mortar bookstore in the midst of an economic meltdown)</p>
        <p><strong>What makes us unique as a bookstore?</strong><br>
        All of our staff are passonate about books and read atleast 3 books a month. We really love books, sometimes more than people. We have a serious thing for science fiction. Areas of specialisation are Non fiction, literature and Science fiction (not necessarily in that order)
        </p>
        <p><strong>What we really dream of?</strong><br>
        More access to books, especially in areas where this is not possible. We run a non profit, called <a href="https://gobookbank.wordpress.com/">Go Book Bank</a>, with the objective of setting up libraries and taking books further, sharing the joy and salvation that books have provided us.
        </p>
        <p><strong>Why should I sign up for this service?</strong><br>
        Well, you benefit from our lifelong love for books and 8 years of being professional (ahem) book curators and sellers.
        </p>

    </div>
</div>
{% endblock %}

apps/base/templates/base/book_form.html
{% extends 'base.html' %}

{% block head %}
  {{ form.media.css }}
{% endblock %}

{% block content %}
<section>
    <form action="" method="post">
        {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h1>Add Book</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
            Please enter the OL ID of the book. It is a string starting with OL and ending in M. We will auto-populate whatever fields we find from the OpenLibrary record for the book. The 'Author - auto' and 'Publisher - auto' are fields which are auto-populated. If you find these fields incorrect or would like to add more Authors, use the autocomplete Authors field.
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
              {{ form.errors }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                OL ID
            </div>
            <div class="col-md-4">
                {{ form.ol_id }}
            </div>
        </div>
        {% include 'base/_form_field.html' with field=form.title %}
        {% include 'base/_form_field.html' with field=form.isbn %}
        {% include 'base/_form_field.html' with field=form.genres %}
        <div class="row">
            <div class="col-md-2">
              Author - auto
            </div>
            <div class="col-md-4">
                <select name="author_auto" multiple="multiple" id="author_auto">
                </select>
            </div>
        </div>
        {% include 'base/_form_field.html' with field=form.authors %}
        <div class="row">
            <div class="col-md-2">
            Publisher - auto
            </div>
            <div class="col-md-4">
              <input name="publisher_auto" type="text" class="form-control" id="publisher_auto"> 
            </div>
        </div>
        {% include 'base/_form_field.html' with field=form.publisher %}
        {% include 'base/_form_field.html' with field=form.year_of_publication %}
        <div class="row">
            <div class="col-md-6 pull-right">
                <button type="submit" name="_addanother" value="add" class="btn btn-secondary">Save and add another</button>
                <button type="submit" name="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
    </form>
</section>
{% endblock %}

{% block scripts %}
  {{ form.media.js }}
<script type="text/javascript">
$(function() {
    $("#id_ol_id").on('input propertychange paste', function() {
        var ol_id = $("#id_ol_id").val();
        if (ol_id.endsWith("M")) {
          $.getJSON("https://openlibrary.org/books/" + ol_id + ".json", function (data) {
              console.log(data);
              $("#id_title").val(data.title);
              if (data.isbn_13) {
                $("#id_isbn").val(data.isbn_13);
              }
              $("#publisher_auto").val(data.publishers[0]);
              $.getJSON("https://openlibrary.org" + data.works[0].key + ".json", function(dataworks) {
                  for (var i=0; i < dataworks.authors.length; i++) {
                    $("#author_auto").append($("<option value='" + dataworks.authors[i].author.key + "' selected='selected'>" + dataworks.authors[0].author.key + "</option>" ));
                  }
              });
          }).error(function(error) { alert("This OL ID does not exist"); });
        }
    });
});
</script>
{% endblock %}

apps/base/templates/base/profile_detail.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load ratings %}

{% block content %}
<section>
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <h1>Profile Details</h1>
          </div>
      </div>
      <div class="row">
          <div class="col-md-4">
            {{ object.user.username }}
          </div>
          {% if user == object.user %}
          <div class="col-md-4">
              <a href="{% url 'profile-edit' %}" class="btn btn-primary">Edit</a>
          </div>
          {% endif %}
      </div>
      {% if user == object.user or user.is_staff %}
      <div class="row">
          <div class="col-md-4">
              <h2>Address/Contact Details</h2>
          </div>
      </div>
      <div class="row">
          <div class="col-md-2">Address</div>
          <div class="col-md-2">{{ object.address|linebreaks }}</div>
      </div>
      <div class="row">
          <div class="col-md-2">City</div>
          <div class="col-md-2">{{ object.city }}</div>
      </div>
      <div class="row">
          <div class="col-md-2">State</div>
          <div class="col-md-2">{{ object.get_state_display }}</div>
      </div>
      <div class="row">
          <div class="col-md-2">PIN Code</div>
          <div class="col-md-2">{{ object.postal_code }}</div>
      </div>
      <div class="row">
          <div class="col-md-2">Mobile</div>
          <div class="col-md-2">{{ object.phone_mobile }}</div>
      </div>
      <div class="row">
          <div class="col-md-2">Landline</div>
          <div class="col-md-2">{{ object.phone_landline }}</div>
      </div>
      <div class="row">
          <div class="col-md-5">
              <h2>Social Accounts</h2>
          </div>
      </div>

      {% get_social_accounts user as accounts %}
      <div class="row well">
          <div class="col-md-6">
          {% if accounts.facebook.0 %}
            Congratulations you have linked your Facebook account
          {% else %}
            No linked Facebook account
            {% if user == object.user %}
            <a href="{% provider_login_url 'facebook' process='connect' %}" class="btn socialaccount_provider facebook">Connect Facebook</a>
            {% endif %}
          {% endif %}
          </div>
      </div>
      <div class="row well">
          <div class="col-md-6">
          {% if accounts.goodreads.0 %}
            Congratulations you have linked your Goodreads account. We can now make useful recommendations based on books you have read and reviewed.
          {% else %}
            There is no linked Goodreads account. Please connect your Goodreads account so we can make useful recommendations based on books you have read and reviewed.
            {% if user == object.user %}
            <a href="{% provider_login_url 'goodreads' process='connect' %}" class="btn socialaccount_provider goodreads">Connect Goodreads</a>
            {% endif %}
          {% endif %}
          </div>
      </div>

      {% if user.is_staff and goodreads %}
      <div class="row">
          <div class='col-md-6'>
              Goodreads profile information: <a href="https://www.goodreads.com/user/show/{{ goodreads.uid }}">link</a><br>
              <ul>
              Goodreads books
              {% for book in goodreads.extra_data.user.updates.update %}
              <li>
                  {% if book.object %}
                  {{ book.object.read_status.review.book.title }} by
                  {{ book.object.read_status.review.book.author.name }} |
                  Rating: {{ book.object.read_status.review.rating }} |
                  Status: {{ book.object.read_status.status }}
                  {% endif %}
              </li>
              {% endfor %}
              </ul>
          </div>
      </div>
      {% endif %}

      {% endif %} {# endif user == object.user #}

      <div class="row">
          <div class="col-md-4">
              <h2>Genres</h2>
          </div>
      </div>
      <div class="row">
          <div class="col-md-4">
            {% for genre in object.genres.all %}
            <li>{{ genre }}</li>
            {% endfor %}
          </div>
      </div>
      <div class="row">
          <div class="col-md-6">
              <h2>Favourite Books and Authors</h2>
          </div>
          {% if user == object.user %}
          <div class="col-md-4">
              <a href="{% url 'profile-edit' %}" style="margin-top: 40px" class="btn btn-primary">Edit</a>
          </div>
          {% endif %}
      </div>
      <div class="row">
          <div class="col-md-2">
              <h3>Books</h3>
            {% for book in object.favourite_books.all %}
              <li>{{ book.title }}</li>
            {% endfor %}
          </div> 
          <div class="col-md-2">
              <h3>Authors</h3>
            {% for author in object.favourite_authors.all %}
              <li>{{ author.name }}</li>
            {% endfor %}
          </div>
      </div>
      <div class="row">
          <div class="col-md-4"><h2>Boxes</h2></div>
      </div>
      {% for box in object.user.box_set.all %}
      {% if box.shipped_at %}
      <div class="row">
          <div class="col-md-4">
              <a href="{% url 'box-review' pk=box.id %}">{{ box.shipped_at }}</a>
              {% ratings box read_only=True %}
          </div>
      </div>
      {% endif %}
      {% endfor %}
  </div>
</section>
{% include "socialaccount/snippets/login_extra.html" %}
{% endblock %}

apps/base/templates/base/profile_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous" />
<style>
label {
  vertical-align: top;
}
</style>
{% endblock %}

{% block content %}
<section id="profile">
 <div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <form action="" method="post">
              {% csrf_token %}
            <ul class="nav nav-tabs" id="wizard">
                <li class="nav-item active">
                    <a href="#address" data-toggle="tab" aria-controls="address" role="tab" title="Address">Address</a>
                </li>
                <li class="nav-item">
                    <a href="#genres" data-toggle="tab" aria-controls="genres" role="tab" title="Genres">Genres</a>
                </li>
                <li class="nav-item">
                    <a href="#favourites" data-toggle="tab" aria-controls="favourites" role="tab" title="Favourites">Favourites</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="address">
                    {{ form.errors }}
                    {% include "base/_form_field.html" with field=form.address %}
                    {% include "base/_form_field.html" with field=form.city %}
                    {% include "base/_form_field.html" with field=form.state %}
                    {% include "base/_form_field.html" with field=form.postal_code %}
                    {% include "base/_form_field.html" with field=form.phone_mobile %}
                    {% include "base/_form_field.html" with field=form.phone_landline %}
                    <div class="row">
                        <div class="col-sm-2 col-sm-offset-4">
                          <a href="#genres" class="btn btn-dark" data-toggle="tab" aria-controls="genres" role="tab" onclick="javascript:stepGenres()">Next</a>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="genres">
                    {{ form.genres }}
                    <div class="row">
                        <div class="col-sm-2">
                          <a href="#address" class="btn btn-light" data-toggle="tab" aria-controls="address" role="tab" onclick="javascript:stepAddress()">Previous</a>
                        </div>
                        <div class="col-sm-2 col-sm-offset-2">
                          <a href="#favourites" class="btn btn-dark" data-toggle="tab" aria-controls="favourites" role="tab" onclick="javascript:stepFavourites()">Next</a>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="favourites">
                    <div class="row">
                        <div class="col-md-3 col-md-offset-2">
                          <img width="320" src="{% static 'img/brain-upload.jpg' %}"> 
                        </div>
                    </div>
                    <div class="row">
                      &nbsp;
                    </div>
                    <div class="row">
                        <div class="col-sm-3"><input class="form-control" placeholder="Book Title" type="text" id="id_books"> </div>
                        <div class="col-sm-3"><input class="form-control" placeholder="Author Name" type="text" id="id_authors"></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3">
                            <select name="favourite_books" multiple="multiple" id="id_favourite_books">
                            {% for book in object.favourite_books.all %}
                            <option value="{{ book.id }}" selected="selected">{{ book.title }}</option>
                            {% endfor %}
                            </select>
                            
                        </div>
                        <div class="col-sm-4 col-sm-offset-1">
                            <select name="favourite_authors" multiple="multiple" id="id_favourite_authors">
                            {% for author in object.favourite_authors.all %}
                            <option value="{{ author.id }}" selected="selected">{{ author.name }}</option>
                            {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        &nbsp;
                    </div>
                    <div class="row">
                        <div class="col-sm-3">Please indicate your other interests, or the names of books or authors you couldn't find in our list above.
                        </div>
                        <div class="col-sm-9">
                            {{ form.interests }}
                        </div>
                    </div>
                    <div class="row">
                      &nbsp;
                    </div>
                    <div class="row">
                        <div class="col-sm-8">
                         This site is a work in progress. Please bear with us - it will be well worth your time! 
                        </div>
                    </div>
                    <div class="row">
                      &nbsp;
                    </div>
                    <div class="row">
                        <div class="col-sm-2">
                    <a href="#genres" class="btn btn-light" data-toggle="tab" aria-controls="genres" role="tab" onclick="javascript:stepGenres()">Previous</a>
                        </div>
                        <div class="col-sm-2 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary" onclick="javascript:submit()">Finish</button>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
 </div>
</section>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>

<script type="text/javascript">
function stepAddress() {
  $("#wizard li").removeClass("active");
  $("#wizard li")[0].classList.add("active");
}

function stepGenres() {
  $("#wizard li").removeClass("active");
  $("#wizard li")[1].classList.add("active");
}

function stepFavourites() {
  $("#wizard li").removeClass("active");
  $("#wizard li")[2].classList.add("active");
}

function submit() {
  $("#id_favourite_books option").prop("selected", true);
  $("#id_favourite_authors aoption").prop("selected", true);
  return false;
}

$(function() {
  var getBooks = function(request, response) {
    $.getJSON("/api/books/?q=" + request.term, function(data) {
      var resp = [];
      var data = JSON.parse(data);
      for(var i in data) {
          resp.push({label: data[i].fields.title, value: data[i].pk});
      }
      response(resp);
    });
  };

  var getAuthors = function(request, response) {
    $.getJSON("/api/authors/?name=" + request.term, function(data) {
      var resp = [];
      var data = JSON.parse(data);
      for(var i in data) {
          resp.push({label: data[i].fields.name, value: data[i].pk});
      }
      response(resp);
    });
  };

  $("#id_books").autocomplete({
    source: getBooks,
    select: function(evt, ui) {
        //ensure that the book is unique in the select
        $("#id_favourite_books option").each(function(i, o) { 
          if (o.value == ui.item.value) {
            $("#id_books").val("");
            return false;
          }
        });
        $("#id_favourite_books").append($("<option value='" + ui.item.value + "' selected='selected'>" + ui.item.label + "</option>"));
        $("#id_books").val("");
        return false;
    },
    minLength: 4
  });

  $("#id_authors").autocomplete({
      source: getAuthors,
      select: function(evt, ui) {
        $("#id_favourite_authors option").each(function(i, o) {
          if (o.value == ui.item.value) {
            $("#id_authors").val("");
            return false;
          }
        });

        $("#id_favourite_authors").append($("<option value='" + ui.item.value + "' selected='selected'>" + ui.item.label + "</option>"));
        $("#id_authors").val("");
        return false;
      },
      minLength: 4
  });
});
</script>
{% endblock %}